[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false
    
    package = "netlify-plugin-fetch-feeds"
 
  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"
 
    # All the feeds we wish to gather for use in the build
 
    [[plugins.inputs.feeds]]
      name = "hawksworx"
      url = "https://hawksworx.com/feed.json"
      ttl = 3600
    [[plugins.inputs.feeds]]
      name = "netlify"
      url = "https://www.netlify.com/blog/index.xml"
      ttl = 86400
